// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGbyvokSU0jOBpRd7z6RhURsJunPM1kI',
    appId: '1:148298996479:web:fee830e9501d70883b8aca',
    messagingSenderId: '148298996479',
    projectId: 'fir-chat-demo02',
    authDomain: 'fir-chat-demo02.firebaseapp.com',
    storageBucket: 'fir-chat-demo02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAD6lUo8sfaDfCydRwCzBEJerySuqAuM',
    appId: '1:148298996479:android:35195dac2cfcaee93b8aca',
    messagingSenderId: '148298996479',
    projectId: 'fir-chat-demo02',
    storageBucket: 'fir-chat-demo02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmh5Zz_zeZRX69dDbyyg9Oe2aj9dJYuT0',
    appId: '1:148298996479:ios:c209ac03a11176f93b8aca',
    messagingSenderId: '148298996479',
    projectId: 'fir-chat-demo02',
    storageBucket: 'fir-chat-demo02.appspot.com',
    iosClientId: '148298996479-4bijtsv5mnmailqn3cn329h3117nnl59.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUdemyChatapp02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmh5Zz_zeZRX69dDbyyg9Oe2aj9dJYuT0',
    appId: '1:148298996479:ios:c209ac03a11176f93b8aca',
    messagingSenderId: '148298996479',
    projectId: 'fir-chat-demo02',
    storageBucket: 'fir-chat-demo02.appspot.com',
    iosClientId: '148298996479-4bijtsv5mnmailqn3cn329h3117nnl59.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUdemyChatapp02',
  );
}
